import { expect, test, type Page } from '@playwright/test'
import { webTerminalWorkspace as workspace } from './web-terminal-fixture'

const data = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jP1sAAAAASUVORK5CYII='
const png = Buffer.from(data, 'base64')
const reference = '/root/.outpost/clipboard/work/image.png'
const bracket = (text: string) => `\x1b[200~${text.replace(/\r?\n/g, '\r')}\x1b[201~\r`


async function pasteImage(page: Page, mediaType = 'image/png', bytes = png) {
  await page.getByLabel('Terminal text', { exact: true }).evaluate((element, image) => {
    const clipboard = new DataTransfer()
    clipboard.items.add(new File([Uint8Array.from(atob(image.data), character => character.charCodeAt(0))], 'clipboard.png', { type: image.mediaType }))
    element.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: clipboard }))
  }, { data: bytes.toString('base64'), mediaType })
}

test('the one-line composer grows for multiline content, preserves paste boundaries, shrinks after sending, and keeps rejected drafts', async ({ page }) => {
  const state = await workspace(page)
  const text = page.getByLabel('Terminal text', { exact: true })
  const originalHeight = (await text.boundingBox())!.height
  expect(originalHeight).toBe(44)
  await expect.poll(() => state.sizes.length).toBeGreaterThan(0)
  const originalRows = state.sizes.at(-1)!.rows
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.evaluate(() => navigator.clipboard.writeText('first line\nsecond line\nthird line'))
  await text.focus()
  await text.press('Control+v')
  await expect(text).toHaveValue('first line\nsecond line\nthird line')
  expect((await text.boundingBox())!.height).toBeGreaterThan(originalHeight)
  await expect.poll(() => state.sizes.at(-1)!.rows).toBeLessThan(originalRows)
  const socketCount = state.sockets.length
  await text.press('Enter')
  await expect(text).toHaveValue('first line\nsecond line\nthird line\n')
  expect(state.inputs).toEqual([])
  await text.dispatchEvent('keydown', { key: 'Enter', ctrlKey: true, isComposing: true })
  expect(state.inputs).toEqual([])
  await text.press('Control+Enter')
  await expect.poll(() => state.inputs).toEqual([bracket('first line\nsecond line\nthird line\n')])
  await expect(text).toHaveValue('')
  await expect.poll(async () => (await text.boundingBox())!.height).toBe(originalHeight)
  await text.fill('command shortcut')
  await text.press('Meta+Enter')
  await expect.poll(() => state.inputs.at(-1)).toBe(bracket('command shortcut'))
  const tooLarge = '漢'.repeat(6000)
  await text.fill(tooLarge)
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('16 KiB')
  await expect(text).toHaveValue(tooLarge)
  expect(state.inputs).toHaveLength(2)
  await text.fill('corrected draft')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => state.inputs.at(-1)).toBe(bracket('corrected draft'))
  expect(state.sockets).toHaveLength(socketCount)
  expect(state.errors).toEqual([])
})

for (const backend of ['tmux', 'dtach'] as const) test(`${backend}: image paste previews and uploads once, keeps the draft during upload, and sends the reference correctly`, async ({ page }) => {
  const state = await workspace(page, { backend })
  const text = page.getByLabel('Terminal text', { exact: true })
  await text.fill('describe this image\nand suggest a fix')
  await pasteImage(page)
  await expect(page.getByAltText('Terminal image preview')).toBeVisible()
  expect(state.uploads).toEqual([])
  await page.getByRole('button', { name: 'Remove image', exact: true }).click()
  await expect(page.getByAltText('Terminal image preview')).toHaveCount(0)
  await expect(text).toHaveValue('describe this image\nand suggest a fix')
  await pasteImage(page)
  let complete!: () => void
  const pending = new Promise<void>(resolve => { complete = resolve })
  state.onUpload(async route => { await pending; await route.fulfill({ json: { path: reference, reference, injected: backend === 'tmux' } }) })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => state.uploads.length).toBe(1)
  await expect(page.getByRole('button', { name: 'Sending…', exact: true })).toBeDisabled()
  await expect(text).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Remove image', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Manage key', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Close dialog', exact: true })).toBeDisabled()
  await page.locator('.terminal-compose').evaluate(form => (form as HTMLFormElement).requestSubmit())
  expect(state.uploads).toHaveLength(1)
  expect(state.inputs).toEqual([])
  complete()
  await expect(text).toHaveValue('')
  await expect(page.getByAltText('Terminal image preview')).toHaveCount(0)
  await expect.poll(() => state.inputs).toEqual([bracket(`${backend === 'tmux' ? '' : reference} describe this image\nand suggest a fix`)])
  expect(state.uploads).toEqual([{ data, mediaType: 'image/png' }])
  await expect(page.getByRole('button', { name: 'Close dialog', exact: true })).toBeEnabled()
  await page.getByLabel('Choose terminal image').setInputFiles({ name: 'gallery.png', mimeType: 'image/png', buffer: png })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => state.inputs.at(-1)).toBe(backend === 'tmux' ? '\r' : bracket(reference))
  expect(state.errors).toEqual([])
})

test('invalid pasted images never upload, failures preserve the image and text, and a network drop retries without uploading again', async ({ page }) => {
  const state = await workspace(page)
  const text = page.getByLabel('Terminal text', { exact: true })
  await text.fill('retained draft')
  await pasteImage(page, 'image/svg+xml', Buffer.from('<svg/>'))
  await expect(page.getByRole('alert')).toContainText('not a PNG')
  await expect(page.getByAltText('Terminal image preview')).toHaveCount(0)
  await page.getByLabel('Choose terminal image').setInputFiles({ name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(16 * 1024 * 1024 + 1) })
  await expect(page.getByRole('alert')).toContainText('16 MB')
  expect(state.uploads).toEqual([])
  await pasteImage(page)
  state.onUpload(route => route.fulfill({ status: 502, json: { message: 'Target unavailable; try again' } }))
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Target unavailable; try again')
  await expect(text).toHaveValue('retained draft')
  await expect(page.getByAltText('Terminal image preview')).toBeVisible()
  expect(state.inputs).toEqual([])
  const socketCount = state.sockets.length
  state.onUpload(async route => {
    state.disconnect()
    await expect(page.locator('.terminal-toolbar')).toContainText('Connection lost')
    await route.fulfill({ json: { path: reference, reference, injected: true } })
  })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Reconnect to send your draft')
  await expect(text).toHaveValue('retained draft')
  await expect.poll(() => state.sockets.length).toBe(socketCount + 1)
  state.reconnect()
  await expect(page.locator('.terminal-toolbar')).toContainText('Connected')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => state.inputs).toEqual([bracket(' retained draft')])
  expect(state.uploads).toHaveLength(2)
  expect(state.errors).toEqual([])
})

test.describe('phone composer', () => {
  test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  test('hosted mode keeps multiline text, images and Send reachable in fullscreen, landscape and with the keyboard open', async ({ page }) => {
    const state = await workspace(page, { hosted: true, backend: 'dtach' })
    await page.getByRole('button', { name: 'Fullscreen', exact: true }).tap()
    const text = page.getByLabel('Terminal text', { exact: true })
    const draft = Array.from({ length: 10 }, (_, index) => `Line ${index + 1}`).join('\n')
    await text.fill(draft)
    await pasteImage(page)
    const socketCount = state.sockets.length
    for (const viewport of [{ width: 390, height: 844 }, { width: 844, height: 390 }, { width: 360, height: 300 }]) {
      await page.setViewportSize(viewport)
      await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeInViewport({ ratio: 1 })
      await expect(page.getByRole('button', { name: 'Remove image', exact: true })).toBeInViewport({ ratio: 1 })
      await expect(page.getByRole('button', { name: 'Close dialog', exact: true })).toBeInViewport({ ratio: 1 })
      expect(await page.getByRole('dialog').evaluate(dialog => dialog.scrollWidth <= dialog.clientWidth)).toBe(true)
      expect((await text.boundingBox())!.height).toBeLessThanOrEqual(viewport.height * .2 + 1)
      expect(await text.evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true)
      expect((await page.locator('.terminal-surface').boundingBox())!.height).toBeGreaterThan(45)
    }
    await page.screenshot({ path: 'test-results/terminal-composer-mobile-keyboard.png' })
    await page.getByRole('button', { name: 'Send', exact: true }).tap()
    await expect.poll(() => state.inputs).toEqual([bracket(`${reference} ${draft}`)])
    await expect(text).toHaveValue('')
    expect((await text.boundingBox())!.height).toBe(44)
    expect(state.uploads).toEqual([{ data, mediaType: 'image/png' }])
    expect(state.sockets).toHaveLength(socketCount)
    expect(state.errors).toEqual([])
  })
})
