import { expect, test } from '@playwright/test'
import { webTerminalWorkspace as workspace } from './web-terminal-fixture'

test('terminal keyboard modifiers work once for physical keys and application-mode arrows', async ({ page }) => {
  const state = await workspace(page)
  const key = (name: string) => page.getByRole('button', { name, exact: true })
  await key('Ctrl').click()
  await page.getByLabel('Terminal input', { exact: true }).press('a')
  await expect.poll(() => state.inputs).toEqual(['\x01'])
  await expect(key('Ctrl')).toHaveAttribute('aria-pressed', 'false')
  await key('Alt').click()
  await page.getByLabel('Terminal input', { exact: true }).press('b')
  await expect.poll(() => state.inputs).toEqual(['\x01', '\x1bb'])
  await expect(key('Alt')).toHaveAttribute('aria-pressed', 'false')
  const acknowledgements = state.acknowledgements.length
  state.sockets.at(-1)!.send(Buffer.from('\x1b[?1h'))
  await expect.poll(() => state.acknowledgements.length).toBeGreaterThan(acknowledgements)
  await key('↑').click()
  await key('Ctrl').click(); await key('Alt').click(); await key('←').click()
  await key('←').click()
  await key('Shift+Enter').click()
  await expect.poll(() => state.inputs.slice(2)).toEqual(['\x1bOA', '\x1b[1;7D', '\x1bOD', '\x1b[13;2u'])
  await expect(key('Ctrl')).toHaveAttribute('aria-pressed', 'false')
  await expect(key('Alt')).toHaveAttribute('aria-pressed', 'false')
  expect(state.errors).toEqual([])
})

test('extra keys provide navigation, shortcuts, symbols and function keys without submitting a draft', async ({ page }) => {
  const state = await workspace(page)
  const key = (name: string) => page.getByRole('button', { name, exact: true })
  await page.getByLabel('Terminal text', { exact: true }).fill('unsent draft')
  await key('More keys').click()
  const panel = page.getByRole('group', { name: 'More terminal keys', exact: true })
  await expect(panel).toBeVisible()
  await key('Home').click(); await key('Delete').click(); await key('Shift+Tab').click()
  await key('Shortcuts').click(); await key('Ctrl+U').click()
  await key('Symbols').click(); await key('|').click()
  await key('F keys').click(); await key('F12').click()
  await expect.poll(() => state.inputs).toEqual(['\x1b[H', '\x1b[3~', '\x1b[Z', '\x15', '|', '\x1b[24~'])
  await expect(page.getByLabel('Terminal text', { exact: true })).toHaveValue('unsent draft')
  await key('More keys').focus(); await key('More keys').press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(key('More keys')).toBeFocused()
  await key('Ctrl').click()
  state.disconnect()
  await expect(key('Ctrl')).toHaveAttribute('aria-pressed', 'false')
  await expect(key('Ctrl')).toBeDisabled()
  await expect(key('Enter')).toBeDisabled()
  expect(state.errors).toEqual([])
})

test.describe('phone terminal keyboard', () => {
  test.use({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
  test('keys fit without horizontal scrolling and preserve native keyboard focus', async ({ page }) => {
    const state = await workspace(page, { hosted: true })
    await page.getByRole('button', { name: 'Fullscreen', exact: true }).tap()
    const keys = page.getByRole('group', { name: 'Terminal keys', exact: true })
    for (const button of await keys.getByRole('button').all()) {
      await expect(button).toBeInViewport({ ratio: 1 })
      const bounds = (await button.boundingBox())!
      expect(bounds.width).toBeGreaterThanOrEqual(44)
      expect(bounds.height).toBeGreaterThanOrEqual(44)
    }
    await page.getByLabel('Terminal text', { exact: true }).focus()
    await page.getByRole('button', { name: '↑', exact: true }).tap()
    await expect(page.getByLabel('Terminal text', { exact: true })).toBeFocused()
    await page.screenshot({ path: 'test-results/terminal-keyboard-phone.png' })
    for (const viewport of [{ width: 844, height: 390 }, { width: 360, height: 300 }]) {
      await page.setViewportSize(viewport)
      await expect(page.getByRole('button', { name: 'Copy', exact: true })).toBeInViewport({ ratio: 1 })
      await expect(page.getByRole('button', { name: 'Paste', exact: true })).toBeInViewport({ ratio: 1 })
      await expect(page.getByRole('button', { name: 'Send', exact: true })).toBeInViewport({ ratio: 1 })
      expect(await keys.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
      expect((await page.locator('.terminal-surface').boundingBox())!.height).toBeGreaterThan(40)
    }
    await page.getByRole('button', { name: 'More keys', exact: true }).tap()
    await expect(page.getByLabel('Terminal text', { exact: true })).toBeFocused()
    await expect(page.getByRole('group', { name: 'More terminal keys', exact: true })).toBeInViewport({ ratio: 1 })
    await page.getByRole('button', { name: 'Symbols', exact: true }).tap()
    await expect(page.getByLabel('Terminal text', { exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Navigate', exact: true }).tap()
    await page.screenshot({ path: 'test-results/terminal-keyboard-compact.png' })
    await page.getByRole('button', { name: 'Home', exact: true }).tap()
    await expect.poll(() => state.inputs).toEqual(['\x1b[A', '\x1b[H'])
    expect(state.errors).toEqual([])
  })
})
