FROM outpost-ssh-test:local
COPY certificates.crt /etc/ssl/certs/ca-certificates.crt
RUN sed -i 's|http://deb.debian.org|https://deb.debian.org|g' /etc/apt/sources.list.d/debian.sources \
    && apt-get update && apt-get install -y --no-install-recommends tmux dtach \
    && rm -rf /var/lib/apt/lists/*
